- build.gradle
- src/main/resources/application.yml
#4 build.gradle 의존성에 mysql 드라이버 미추가로 인해 발생한 오류
> [CHORE] 도커 환경세팅 오류 해결

- build.gradle
- src/main/java/com/kusitms/backend/controller/AuthController.java
- src/main/java/com/kusitms/backend/domain/User.java
- src/main/java/com/kusitms/backend/dto/AuthDto.java
- src/main/java/com/kusitms/backend/repository/UserRepository.java
- src/main/java/com/kusitms/backend/service/AuthService.java
- src/main/resources/application.yml
> feat: local register

- .gitignore
- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/com/kusitms/backend/InitUser.java
- src/main/java/com/kusitms/backend/config/CustomUserDetailService.java
- src/main/java/com/kusitms/backend/config/JwtAccessDeniedHandler.java
- src/main/java/com/kusitms/backend/config/JwtAuthenticationEntryPoint.java
- src/main/java/com/kusitms/backend/config/JwtFilter.java
- src/main/java/com/kusitms/backend/config/JwtSecurityConfig.java
- src/main/java/com/kusitms/backend/config/SecurityConfig.java
- src/main/java/com/kusitms/backend/config/SecurityUtil.java
- src/main/java/com/kusitms/backend/config/TokenProvider.java
- src/main/java/com/kusitms/backend/controller/AuthController.java
- src/main/java/com/kusitms/backend/domain/Authority.java
- src/main/java/com/kusitms/backend/domain/MetaEntity.java
- src/main/java/com/kusitms/backend/domain/User.java
- src/main/java/com/kusitms/backend/dto/AuthDto.java
- src/main/java/com/kusitms/backend/dto/SignInRequest.java
- src/main/java/com/kusitms/backend/dto/TokenDto.java
- src/main/java/com/kusitms/backend/exception/ApiException.java
- src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
- src/main/java/com/kusitms/backend/exception/GlobalExceptionHandler.java
- src/main/java/com/kusitms/backend/repository/UserRepository.java
- src/main/java/com/kusitms/backend/response/BaseResponse.java
- src/main/java/com/kusitms/backend/response/ExceptionResponse.java
- src/main/java/com/kusitms/backend/service/AuthService.java
- src/main/java/com/kusitms/backend/service/IAuthService.java
- src/main/java/com/kusitms/backend/util/RedisClient.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
#3 
authorization  속성에 토큰 값 세팅
> [FEAT] 로컬 로그인 구현 및 머지 충돌 해결

- src/main/java/com/kusitms/backend/InitUser.java
- src/main/java/com/kusitms/backend/domain/Address.java
- src/main/java/com/kusitms/backend/domain/Authority.java
- src/main/java/com/kusitms/backend/domain/Comment.java
- src/main/java/com/kusitms/backend/domain/Deal.java
- src/main/java/com/kusitms/backend/domain/House.java
- src/main/java/com/kusitms/backend/domain/HousePost.java
- src/main/java/com/kusitms/backend/domain/ImageFile.java
- src/main/java/com/kusitms/backend/domain/Notice.java
- src/main/java/com/kusitms/backend/domain/Post.java
- src/main/java/com/kusitms/backend/domain/Region.java
- src/main/java/com/kusitms/backend/domain/RegionPost.java
- src/main/java/com/kusitms/backend/domain/ReviewPost.java
- src/main/java/com/kusitms/backend/domain/Tour.java
- src/main/java/com/kusitms/backend/domain/User.java
- src/main/resources/application-local.yml
> [CHORE] 도메인 생성

- src/main/java/com/kusitms/backend/BackendApplication.java
- src/main/java/com/kusitms/backend/config/JwtAccessDeniedHandler.java
- src/main/java/com/kusitms/backend/config/TokenProvider.java
- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/domain/Address.java
- src/main/java/com/kusitms/backend/domain/Comment.java
- src/main/java/com/kusitms/backend/domain/House.java
- src/main/java/com/kusitms/backend/domain/HousePost.java
- src/main/java/com/kusitms/backend/domain/ImageFile.java
- src/main/java/com/kusitms/backend/domain/Post.java
- src/main/java/com/kusitms/backend/domain/Region.java
- src/main/java/com/kusitms/backend/domain/RegionPost.java
- src/main/java/com/kusitms/backend/domain/User.java
- src/main/java/com/kusitms/backend/dto/HouseDto.java
- src/main/java/com/kusitms/backend/repository/HouseRepository.java
- src/main/java/com/kusitms/backend/repository/ImageFileRepository.java
- src/main/java/com/kusitms/backend/repository/PostRepository.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
- 빈 집 게시글 생성
- 이미지 객체 생성
- 시큐리티 설정 오류 수정
- jpa auditing 수정
- 테이블 관계 수정
> [FEAT] 빈 집 게시글 생성 API

- src/main/java/com/kusitms/backend/controller/RegionController.java
- src/main/java/com/kusitms/backend/domain/HousePost.java
- src/main/java/com/kusitms/backend/domain/Region.java
- src/main/java/com/kusitms/backend/dto/HouseDto.java
- src/main/java/com/kusitms/backend/dto/RegionDto.java
- src/main/java/com/kusitms/backend/repository/RegionRepository.java
- src/main/java/com/kusitms/backend/service/AuthService.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IRegionService.java
- src/main/java/com/kusitms/backend/service/RegionService.java
> [FEAT] 지역 생성 API

- src/main/java/com/kusitms/backend/config/JwtFilter.java
- src/main/java/com/kusitms/backend/config/SecurityConfig.java
- src/main/java/com/kusitms/backend/config/SecurityUtil.java
- src/main/java/com/kusitms/backend/config/TokenProvider.java
- src/main/java/com/kusitms/backend/controller/AuthController.java
- src/main/java/com/kusitms/backend/dto/TokenDto.java
- src/main/java/com/kusitms/backend/dto/TokenRequestDto.java
- src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
- src/main/java/com/kusitms/backend/service/AuthService.java
- src/main/java/com/kusitms/backend/service/IAuthService.java
- src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
> [FEAT] 로컬 로그인 + JWT + Redis

- .gitignore
- src/docs/asciidoc/api-doc.adoc
- src/main/java/com/kusitms/backend/dto/CheckSmsRequest.java
- src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
> [TEST] 전화번호 인증코드 전송 & 검증 API 문서화

- src/docs/asciidoc/api-doc.adoc
- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/dto/HouseDto.java
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> [TEST] 빈 집 게시글 작성 API 문서화

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/S3ControllerTest.java
> [TEST] AWS S3 이미지 업로드 & 삭제 API 문서화

- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/domain/Deal.java
- src/main/java/com/kusitms/backend/domain/DealState.java
- src/main/java/com/kusitms/backend/dto/DealDto.java
- src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
- src/main/java/com/kusitms/backend/repository/DealRepository.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
> [FEAT] 거래 생성 API

- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/domain/Deal.java
- src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
> [FEAT] 거래 완료 API

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
- src/test/java/com/kusitms/backend/controller/RegionControllerTest.java
> [TEST] 거래 생성 API 문서화

- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
> [FEAT] 빈 집 게시글 상세 조회 API

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> [TEST] 빈 집 거래 완료 API 문서화

- docker-compose.yml
- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/domain/Address.java
- src/main/java/com/kusitms/backend/domain/House.java
- src/main/java/com/kusitms/backend/dto/HousePreviewDto.java
- src/main/java/com/kusitms/backend/repository/HousePostRepository.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
- src/test/java/com/kusitms/backend/controller/RegionControllerTest.java
> [FEAT] 빈 집 게시글 페이징 처리 API

- src/docs/asciidoc/api-doc.adoc
- src/main/java/com/kusitms/backend/config/SecurityConfig.java
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> [TEST] 빈 집 게시글 목록 조회 API 문서화

- docker-compose-local.yml
- docker-compose.yml
- src/main/java/com/kusitms/backend/controller/AuthController.java
- src/main/java/com/kusitms/backend/dto/SignInRequest.java
- src/main/java/com/kusitms/backend/dto/TokenDto.java
- src/main/java/com/kusitms/backend/service/AuthService.java
- src/main/java/com/kusitms/backend/service/IAuthService.java
- src/main/java/com/kusitms/backend/util/OauthClient.java
- src/main/resources/application-local.yml
> [FIX] 카카오 소셜 로그인 수정

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/ReviewControllerTest.java
> test: Create get review post detail API docs file

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/ReviewControllerTest.java
> test: Create get review post list API docs file

- src/main/java/com/kusitms/backend/InitUser.java
- src/main/java/com/kusitms/backend/config/SecurityConfig.java
- src/main/java/com/kusitms/backend/controller/RegionController.java
- src/main/java/com/kusitms/backend/service/IRegionService.java
- src/main/java/com/kusitms/backend/service/RegionService.java
> feat: Create get region post detail api

- src/docs/asciidoc/api-doc.adoc
- src/main/java/com/kusitms/backend/config/SecurityConfig.java
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
- 토큰 불필요 패스 설정
- 빈 집 게시글 목록 조회 페이징 데이터 추가
- 빈 집 게시글 생성 -> 매매
- 빈 집 게시글 생성 -> 월세
> [DOCS] 빈 집 게시글 문서화 코드 수정

- src/docs/asciidoc/api-doc.adoc
- src/main/java/com/kusitms/backend/dto/TokenRequestDto.java
- src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
> [DOCS] 토큰 재발급 API 문서화

- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> Dual 98, Dual 114

- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/domain/House.java
- src/main/java/com/kusitms/backend/domain/HousePost.java
- src/main/java/com/kusitms/backend/dto/HouseDto.java
- src/main/java/com/kusitms/backend/repository/DealRepository.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> refactor: Modify get house post detail API

- src/main/java/com/kusitms/backend/config/TokenProvider.java
- src/main/java/com/kusitms/backend/service/AuthService.java
> [FIX] 토큰 재발급 API 수정

- build.gradle
- src/main/java/com/kusitms/backend/BackendApplication.java
- src/main/java/com/kusitms/backend/util/LoggingAspect.java
> [CHORE] AOP를 이용한 로깅 적용

- src/main/java/com/kusitms/backend/service/HouseService.java
> refactor: Modify get house post detail service

- src/main/java/com/kusitms/backend/controller/HouseController.java
- src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
- src/main/java/com/kusitms/backend/repository/HousePostRepository.java
- src/main/java/com/kusitms/backend/service/HouseService.java
- src/main/java/com/kusitms/backend/service/IHouseService.java
> [FEAT] 내가 작성한 빈 집 게시글 리스트 조회 API

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> [DOCS] 본인이 작성한 빈 집 게시글 목록 조회 API 문서화

- src/main/java/com/kusitms/backend/dto/HouseDto.java
> refactor: Add house post validation

- src/docs/asciidoc/api-doc.adoc
- src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
> test: Create get house post detail API docs

- src/main/java/com/kusitms/backend/repository/UserRepository.java
- src/main/java/com/kusitms/backend/service/AuthService.java
- src/main/java/com/kusitms/backend/util/OauthClient.java
> [FIX] 전화번호 등록 여부 확인 로직 수정
